site_name: Nina's Cheetsheats

nav:
    - Home: index.md
    - Numpy: numpy.md
    - Pandas: pandas.md
theme: 
    name: readthedocs
#     sticky_navigation: False
#     collapse_navigation: False
#     titles_only: False
    highlightjs: True
    hljs_languages:
        - yaml
        - django
    
extra_css:
    - css/extra.css